import type * as vscode from "vscode";
import type { SelectionGroup } from "./types";
import { localize, type UiLanguage } from "./uiLanguage";
import { createWebviewNonce } from "./webviewCommon";
import { renderWebviewCommonStyles } from "./webviewCommonStyles";

type GroupSource = SelectionGroup["meta"] extends undefined ? string : NonNullable<SelectionGroup["meta"]>["source"];

export type GroupInfoRow = {
  targetPath: string;
  kind: string;
  fileMtime: string;
  fileSize: string;
  latestAt: string;
  latestProject: string;
  latestSource: string;
};

export type GroupInfoPanelData = {
  name: string;
  description: string;
  side: "workspace" | "central";
  count: number;
  source: GroupSource | string;
  repoKey: string;
  repoUrl: string;
  lastInstalledAt: string;
  mirroredFrom: string;
  rows: GroupInfoRow[];
};

export function sanitizeGroupMeta(meta: unknown): SelectionGroup["meta"] {
  if (!meta || typeof meta !== "object") return undefined;
  const source = (meta as { source?: unknown }).source;
  const tool = (meta as { tool?: unknown }).tool;
  const repoKey = (meta as { repoKey?: unknown }).repoKey;
  const repoUrl = (meta as { repoUrl?: unknown }).repoUrl;
  const lastInstalledAt = (meta as { lastInstalledAt?: unknown }).lastInstalledAt;
  const installCwd = (meta as { installCwd?: unknown }).installCwd;
  const installSkills = (meta as { installSkills?: unknown }).installSkills;
  const mirroredFrom = (meta as { mirroredFrom?: unknown }).mirroredFrom;
  const normalized: NonNullable<SelectionGroup["meta"]> = {};
  if (source === "manual" || source === "npx" || source === "mixed") normalized.source = source;
  if (typeof tool === "string" && tool.trim()) normalized.tool = tool as NonNullable<SelectionGroup["meta"]>["tool"];
  if (typeof repoKey === "string" && repoKey.trim()) normalized.repoKey = repoKey.trim();
  if (typeof repoUrl === "string" && repoUrl.trim()) normalized.repoUrl = repoUrl.trim();
  if (typeof lastInstalledAt === "string" && lastInstalledAt.trim()) normalized.lastInstalledAt = lastInstalledAt.trim();
  if (typeof installCwd === "string" && installCwd.trim()) normalized.installCwd = installCwd.trim();
  if (Array.isArray(installSkills)) {
    const skills = installSkills.filter((item): item is string => typeof item === "string" && item.trim().length > 0).map((item) => item.trim());
    if (skills.length > 0) normalized.installSkills = [...new Set(skills)];
  }
  if (typeof mirroredFrom === "string" && mirroredFrom.trim()) normalized.mirroredFrom = mirroredFrom.trim();
  return Object.keys(normalized).length > 0 ? normalized : undefined;
}

export function formatGroupSourceLabel(source: GroupSource | string, language: UiLanguage = "en"): string {
  void language;
  if (source === "npx") return localize("npx install");
  if (source === "mixed") return localize("Mixed");
  if (source === "manual") return localize("Manual");
  return String(source ?? localize("Manual"));
}

export function formatMirroredFromLabel(mirroredFrom: string | undefined, language: UiLanguage = "en"): string {
  if (!mirroredFrom || mirroredFrom === "-") return "-";
  void language;
  if (mirroredFrom === "central-pack" || mirroredFrom === "central-preset") return localize("Central preset");
  if (mirroredFrom.startsWith("workspace:")) {
    return localize("Workspace group applied ({0})", mirroredFrom);
  }
  if (mirroredFrom.startsWith("central:")) {
    return localize("Central group applied ({0})", mirroredFrom);
  }
  return mirroredFrom;
}

export function renderSkillGroupMarkdown(groups: SelectionGroup[], language: UiLanguage = "en"): string {
  void language;
  const tr = formatEnglishMessage;
  const lines: string[] = [
    `# ${tr("Skill Groups")}`,
    "",
    tr("This file is generated by Skill Bridge from `.skillbridge/skill-workspace.json` so agents and search tools can discover how skills are grouped."),
    tr("Groups are metadata and intent, not just file copies, so keep group descriptions current even when the same skill files already exist on both sides."),
    "",
    tr("Update groups through Skill Bridge commands or by updating `.skillbridge/skill-workspace.json`, then regenerate this file."),
    "",
    `## ${tr("Summary")}`,
    "",
    `- ${tr("Groups")}: ${groups.length}`,
    `- ${tr("Workspace groups")}: ${groups.filter((group) => group.side === "workspace").length}`,
    `- ${tr("Central groups")}: ${groups.filter((group) => group.side === "central").length}`,
    ""
  ];

  if (groups.length === 0) {
    lines.push(tr("No skill groups are defined yet."), "");
    return `${lines.join("\n")}\n`;
  }

  const sortedGroups = [...groups].sort((a, b) => a.side.localeCompare(b.side) || a.name.localeCompare(b.name));
  for (const group of sortedGroups) {
    lines.push(`## ${markdownText(group.name)}`);
    lines.push("");
    lines.push(`- ${tr("ID")}: \`${markdownCode(group.id)}\``);
    lines.push(`- ${tr("Side")}: \`${group.side}\``);
    lines.push(`- ${tr("Description")}: ${group.description ? markdownText(group.description) : "-"}`);
    lines.push(`- ${tr("Targets")}: ${group.targets.length}`);
    const tools = [...new Set(group.targets.map((target) => target.tool))].sort((a, b) => a.localeCompare(b));
    lines.push(`- ${tr("Agents")}: ${tools.map((tool) => `\`${tool}\``).join(", ") || "-"}`);
    const metaLines = renderGroupMetaLines(group.meta, language);
    if (metaLines.length > 0) {
      lines.push(`- ${tr("Metadata")}:`);
      lines.push(...metaLines.map((line) => `  - ${line}`));
    }
    lines.push("");
    lines.push(`| ${tr("Agent")} | ${tr("Kind")} | ${tr("Path")} |`);
    lines.push("| --- | --- | --- |");
    for (const target of [...group.targets].sort((a, b) => a.tool.localeCompare(b.tool) || a.relativePath.localeCompare(b.relativePath))) {
      lines.push(`| \`${target.tool}\` | \`${target.kind}\` | \`${markdownTableCode(target.relativePath)}\` |`);
    }
    lines.push("");
  }

  return `${lines.join("\n")}\n`;
}

export function renderGroupInfoHtml(
  webview: vscode.Webview,
  data: GroupInfoPanelData,
  language: UiLanguage = "en",
  options: { scriptsEnabled?: boolean } = {}
): string {
  void webview;
  const esc = (value: string): string =>
    value
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;");
  const t = localize;
  const sourceLabel = formatGroupSourceLabel(data.source, language);
  const mirroredFromLabel = formatMirroredFromLabel(data.mirroredFrom, language);
  const scriptsEnabled = options.scriptsEnabled ?? true;
  const nonce = createWebviewNonce();
  const rowHtml = data.rows.map((row) => {
    const kindLabel = row.kind === "file"
      ? t("file")
      : row.kind === "folder"
        ? t("folder")
        : row.kind;
    const noHistory = row.latestProject === "No history" || row.latestProject === localize("No history") || row.latestAt === "-";
    const searchText = `${data.name} ${data.description} ${row.targetPath} ${row.kind} ${row.latestProject} ${row.latestSource}`;
    return `
      <tr data-search="${esc(searchText.toLowerCase())}" data-history="${noHistory ? "missing" : "known"}">
        <td><span class="path">${esc(row.targetPath)}</span><button class="copy" data-copy="${esc(row.targetPath)}" title="${esc(t("Copy path"))}">${esc(t("Copy"))}</button></td>
        <td>${esc(kindLabel)}</td>
        <td>${esc(row.fileMtime)}</td>
        <td>${esc(row.fileSize)}</td>
        <td>${esc(row.latestAt)}</td>
        <td>${esc(row.latestProject)}</td>
        <td><span class="path">${esc(row.latestSource)}</span><button class="copy" data-copy="${esc(row.latestSource)}" title="${esc(t("Copy path"))}">${esc(t("Copy"))}</button></td>
      </tr>
  `;
  }).join("");

  return `<!doctype html>
<html lang="${language}">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src ${scriptsEnabled ? `'nonce-${nonce}'` : "'none'"};" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${esc(t("Skill Group Info"))}</title>
  <style>${renderWebviewCommonStyles()}
    *, *::before, *::after { box-sizing: border-box; }
    body { font-family: var(--vscode-font-family); color: var(--vscode-foreground); background: var(--vscode-editor-background); margin: 0; height: 100vh; overflow: hidden; }
    .wrap { height: 100vh; padding: 10px; display: grid; gap: 8px; grid-template-rows: auto auto auto auto minmax(0, 1fr); }
    .head { display: flex; justify-content: space-between; align-items: center; gap: 10px; min-width: 0; flex-wrap: wrap; }
    h2 { margin: 0; font-size: 16px; min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
    .pills { display: flex; gap: 6px; align-items: center; overflow-x: auto; scrollbar-gutter: stable; }
    .pill { border: 1px solid var(--vscode-panel-border); border-radius: 999px; padding: 3px 8px; font-size: 11px; color: var(--vscode-descriptionForeground); white-space: nowrap; }
    .pill strong { color: var(--vscode-foreground); }
    .controls { display: flex; gap: 6px; align-items: center; flex-wrap: wrap; }
    .desc { border: 1px solid var(--vscode-panel-border); border-radius: 7px; padding: 8px 10px; color: var(--vscode-descriptionForeground); font-size: 12px; line-height: 1.5; }
    .desc b { color: var(--vscode-foreground); }
    input, button { background: var(--vscode-input-background); color: var(--vscode-input-foreground); border: 1px solid var(--vscode-panel-border); border-radius: 5px; padding: 5px 8px; font: inherit; }
    input { min-width: min(360px, 58vw); max-width: 100%; }
    input[type="checkbox"] { min-width: 0; }
    button { cursor: pointer; }
    button:disabled { opacity: .5; cursor: default; }
    .meta { border: 1px solid var(--vscode-panel-border); border-radius: 7px; padding: 6px 8px; display: flex; gap: 10px; overflow-x: auto; color: var(--vscode-descriptionForeground); font-size: 12px; scrollbar-gutter: stable; }
    .meta b { color: var(--vscode-foreground); }
    .meta-row { white-space: nowrap; }
    .table-wrap { border: 1px solid var(--vscode-panel-border); border-radius: 7px; overflow: auto; min-height: 0; }
    table { width: 100%; border-collapse: collapse; font-size: 12px; }
    th, td { text-align: left; padding: 7px 8px; border-bottom: 1px solid var(--vscode-panel-border); vertical-align: top; }
    thead { background: var(--vscode-sideBar-background); position: sticky; top: 0; z-index: 1; }
    tbody tr:hover { background: var(--vscode-list-hoverBackground); }
    .path { display: inline-block; max-width: 360px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; vertical-align: bottom; }
    .copy { margin-left: 6px; padding: 2px 6px; font-size: 11px; }
    .hidden-row { display: none; }
    @media (max-width: 760px) {
      .controls { align-items: stretch; }
      input { min-width: 100%; }
      table { min-width: 900px; }
      .path { max-width: 56vw; }
    }
  </style>
</head>
<body>
  <div class="wrap sb-root">
    <div class="head sb-topbar">
      <h2 title="${esc(data.name)}">${esc(t("Skill Group Info"))}: ${esc(data.name)}</h2>
      <div id="visibleCount" class="pill sb-chip">${esc(t("Rows"))} ${data.rows.length}</div>
    </div>
    <div class="pills">
      <span class="pill sb-chip">${esc(t("Location"))} <strong>${esc(data.side === "workspace" ? t("Workspace") : t("Central"))}</strong></span>
      <span class="pill sb-chip">${esc(t("Targets"))} <strong>${data.count}</strong></span>
      <span class="pill sb-chip">${esc(t("Source"))} <strong>${esc(sourceLabel)}</strong></span>
      <span class="pill sb-chip">${esc(t("Repo"))} <strong>${esc(data.repoKey)}</strong></span>
    </div>
    <div class="controls">
      <input id="search" placeholder="${esc(t("Search path, project, or source..."))}" />
      <label class="pill sb-chip"><input id="historyOnly" type="checkbox" /> ${esc(t("No history only"))}</label>
    </div>
    <div class="desc"><b>${esc(t("Description:"))}</b> ${esc(data.description || "-")}</div>
    <div class="meta">
      <div class="meta-row"><b>${esc(t("Repo URL:"))}</b> ${esc(data.repoUrl)}</div>
      <div class="meta-row"><b>${esc(t("Last Installed:"))}</b> ${esc(data.lastInstalledAt)}</div>
      <div class="meta-row"><b>${esc(t("Mirrored From:"))}</b> ${esc(mirroredFromLabel)}</div>
    </div>
    <div class="table-wrap sb-table-wrap">
      <table>
        <thead>
          <tr>
            <th>${esc(t("Path"))}</th>
            <th>${esc(t("Type"))}</th>
            <th>${esc(t("File Modified"))}</th>
            <th>${esc(t("File Size"))}</th>
            <th>${esc(t("Latest History"))}</th>
            <th>${esc(t("Latest Project"))}</th>
            <th>${esc(t("Latest Source Path"))}</th>
          </tr>
        </thead>
        <tbody>${rowHtml || `<tr><td colspan="7">${esc(t("No items to show."))}</td></tr>`}</tbody>
      </table>
    </div>
  </div>
  ${scriptsEnabled ? `<script nonce="${nonce}">
    const rows = Array.from(document.querySelectorAll("tbody tr[data-search]"));
    const search = document.getElementById("search");
    const historyOnly = document.getElementById("historyOnly");
    const visibleCount = document.getElementById("visibleCount");
    function applyFilters(){
      const q = search instanceof HTMLInputElement ? search.value.trim().toLowerCase() : "";
      const onlyMissing = historyOnly instanceof HTMLInputElement ? historyOnly.checked : false;
      let visible = 0;
      for (const row of rows) {
        const matchSearch = !q || String(row.getAttribute("data-search") || "").includes(q);
        const matchHistory = !onlyMissing || row.getAttribute("data-history") === "missing";
        const show = matchSearch && matchHistory;
        row.classList.toggle("hidden-row", !show);
        if (show) visible += 1;
      }
      if (visibleCount) visibleCount.textContent = ${JSON.stringify(localize("Rows"))} + " " + visible;
    }
    search?.addEventListener("input", applyFilters);
    historyOnly?.addEventListener("change", applyFilters);
    document.body.addEventListener("click", async (event) => {
      const target = event.target;
      const button = target instanceof Element ? target.closest("button[data-copy]") : null;
      if (!(button instanceof HTMLButtonElement)) return;
      const value = button.getAttribute("data-copy") || "";
      if (!value) return;
      try {
        await navigator.clipboard.writeText(value);
        button.textContent = ${JSON.stringify(localize("Copied"))};
        setTimeout(() => { button.textContent = ${JSON.stringify(localize("Copy"))}; }, 1000);
      } catch {}
    });
    applyFilters();
  </script>` : ""}
</body>
</html>`;
}

function renderGroupMetaLines(meta: SelectionGroup["meta"], language: UiLanguage): string[] {
  const tr = localize;
  if (!meta) return [];
  const lines: string[] = [];
  if (meta.source) lines.push(`${tr("Source")}: ${markdownText(formatGroupSourceLabel(meta.source, language))} (\`${markdownCode(meta.source)}\`)`);
  if (meta.tool) lines.push(`${tr("Agent")}: \`${markdownCode(meta.tool)}\``);
  if (meta.repoKey) lines.push(`${tr("Repo key")}: \`${markdownCode(meta.repoKey)}\``);
  if (meta.repoUrl) lines.push(`${tr("Repo URL")}: ${markdownText(meta.repoUrl)}`);
  if (meta.lastInstalledAt) lines.push(`${tr("Last installed")}: \`${markdownCode(meta.lastInstalledAt)}\``);
  if (meta.mirroredFrom) lines.push(`${tr("Mirrored from")}: ${markdownText(formatMirroredFromLabel(meta.mirroredFrom, language))}`);
  return lines;
}

function markdownText(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/\[/g, "\\[").replace(/\]/g, "\\]");
}

function markdownCode(value: string): string {
  return value.replace(/`/g, "\\`");
}

function markdownTableCode(value: string): string {
  return markdownCode(value).replace(/\|/g, "\\|");
}

function formatEnglishMessage(message: string, ...args: Array<string | number | boolean>): string {
  return message.replace(/\{(\d+)\}/g, (_match, index: string) => String(args[Number(index)] ?? ""));
}
