import { spawn } from "node:child_process";

type TranslationFn = (message: string, ...args: Array<string | number | boolean>) => string;

export type NpxSkillLibraryRequirementStatus = "ok" | "warn" | "missing";

export type NpxSkillLibraryRequirement = {
  id: "node" | "npm" | "npx" | "git" | "skillsPackage";
  label: string;
  status: NpxSkillLibraryRequirementStatus;
  detail: string;
  installScript?: string;
};

export type NpxSkillLibraryDiagnosis = {
  status: "ready" | "blocked";
  osLabel: string;
  checkedAt: string;
  summary: string;
  requirements: NpxSkillLibraryRequirement[];
};

type CommandResult = {
  stdout: string;
  stderr: string;
};

export async function collectNpxSkillLibraryDiagnosis(args: {
  tr: TranslationFn;
  toUserError: (error: unknown) => string;
}): Promise<NpxSkillLibraryDiagnosis> {
  const node = await checkRequiredCommand({
    id: "node",
    label: "Node.js",
    command: "node",
    versionArgs: ["--version"],
    minimumMajorVersion: 18,
    installScript: nodeInstallScript(),
    missingDetail: args.tr("Node.js 18+ is required to run npx skills add."),
    args
  });
  const npm = await checkRequiredCommand({
    id: "npm",
    label: "npm",
    command: "npm",
    versionArgs: ["--version"],
    installScript: nodeInstallScript(),
    missingDetail: args.tr("npm is required because npx is distributed with npm."),
    args
  });
  const npx = await checkRequiredCommand({
    id: "npx",
    label: "npx",
    command: "npx",
    versionArgs: ["--version"],
    installScript: nodeInstallScript(),
    missingDetail: args.tr("npx is required to install and update external skill packs."),
    args
  });
  const git = await checkRequiredCommand({
    id: "git",
    label: "Git",
    command: "git",
    versionArgs: ["--version"],
    installScript: gitInstallScript(),
    missingDetail: args.tr("Git is required by GitHub-based skill repositories and update flows."),
    args
  });
  const skillsPackage = await checkSkillsPackage(args, npm.status === "ok");
  const requirements = [node, npm, npx, git, skillsPackage];
  const missingCount = requirements.filter((item) => item.status === "missing").length;
  const warnCount = requirements.filter((item) => item.status === "warn").length;

  return {
    status: missingCount > 0 ? "blocked" : "ready",
    osLabel: osLabel(),
    checkedAt: new Date().toISOString(),
    summary: missingCount > 0
      ? args.tr("Missing {0} required item(s).", String(missingCount))
      : warnCount > 0
        ? args.tr("Ready with {0} warning(s).", String(warnCount))
        : args.tr("Ready to use npx skill library features."),
    requirements
  };
}

export function renderNpxSkillLibraryGuideMarkdown(diagnosis: NpxSkillLibraryDiagnosis, tr: TranslationFn): string {
  const missing = diagnosis.requirements.filter((item) => item.status === "missing");
  const warnings = diagnosis.requirements.filter((item) => item.status === "warn");
  const scripts = uniqueScripts(missing);
  const lines = [
    "# NPX Skill Library Environment Guide",
    "",
    tr("This guide is generated by Skill Bridge so another agent or operator can inspect the local environment before using NPX skill library updates."),
    "",
    "## Summary",
    "",
    `- ${tr("Status")}: ${diagnosis.status}`,
    `- ${tr("OS")}: ${diagnosis.osLabel}`,
    `- ${tr("Checked at")}: ${diagnosis.checkedAt}`,
    `- ${tr("Result")}: ${diagnosis.summary}`,
    "",
    "## Checks",
    "",
    ...diagnosis.requirements.map((item) => `- [${item.status.toUpperCase()}] ${item.label}: ${item.detail}`),
    "",
    "## Guidance",
    "",
    tr("Do not install or upgrade anything automatically. Review the checks above, confirm the target OS and package manager, then ask the user before running any command."),
    ""
  ];

  if (warnings.length > 0) {
    lines.push("## Warnings", "");
    lines.push(...warnings.map((item) => `- ${item.label}: ${item.detail}`), "");
  }

  if (scripts.length > 0) {
    lines.push("## OS-Specific Command Candidates", "");
    lines.push(tr("These commands are candidates for the current OS, not commands that Skill Bridge has run."), "");
    for (const script of scripts) {
      lines.push(`### ${script.labels.join(", ")}`, "", "```sh", script.script, "```", "");
    }
  } else {
    lines.push("## OS-Specific Command Candidates", "", tr("No missing required command was found, so no install command candidate is included."), "");
  }

  lines.push("## Recommended Next Step", "");
  lines.push(diagnosis.status === "ready"
    ? tr("NPX skill library download/update controls can be used. If an update still fails, inspect the Output panel and network/npm registry settings.")
    : tr("Fix the missing requirements first, restart VS Code if PATH changed, then run the NPX Skill Library check again."));
  lines.push("");
  return `${lines.join("\n")}\n`;
}

function uniqueScripts(requirements: NpxSkillLibraryRequirement[]): Array<{ labels: string[]; script: string }> {
  const byScript = new Map<string, string[]>();
  for (const requirement of requirements) {
    if (!requirement.installScript) continue;
    const labels = byScript.get(requirement.installScript) ?? [];
    labels.push(requirement.label);
    byScript.set(requirement.installScript, labels);
  }
  return [...byScript.entries()].map(([script, labels]) => ({ labels, script }));
}

async function checkRequiredCommand(input: {
  id: NpxSkillLibraryRequirement["id"];
  label: string;
  command: string;
  versionArgs: string[];
  minimumMajorVersion?: number;
  installScript: string;
  missingDetail: string;
  args: { tr: TranslationFn; toUserError: (error: unknown) => string };
}): Promise<NpxSkillLibraryRequirement> {
  try {
    const result = await runCommand(input.command, input.versionArgs, 30000);
    const versionText = (result.stdout || result.stderr).trim();
    const majorVersion = parseMajorVersion(versionText);
    if (input.minimumMajorVersion !== undefined && majorVersion !== null && majorVersion < input.minimumMajorVersion) {
      return {
        id: input.id,
        label: input.label,
        status: "missing",
        detail: input.args.tr("{0} {1}+ is required. Current version: {2}", String(input.label), String(input.minimumMajorVersion), String(versionText)),
        installScript: input.installScript
      };
    }
    return {
      id: input.id,
      label: input.label,
      status: "ok",
      detail: versionText || input.args.tr("{0} is available.", String(input.label))
    };
  } catch (error) {
    return {
      id: input.id,
      label: input.label,
      status: "missing",
      detail: `${input.missingDetail} ${input.args.toUserError(error)}`,
      installScript: input.installScript
    };
  }
}

async function checkSkillsPackage(args: {
  tr: TranslationFn;
  toUserError: (error: unknown) => string;
}, canUseNpm: boolean): Promise<NpxSkillLibraryRequirement> {
  if (!canUseNpm) {
    return {
      id: "skillsPackage",
      label: "skills package",
      status: "warn",
      detail: args.tr("Skipped npm registry check because npm is unavailable.")
    };
  }
  try {
    const result = await runCommand("npm", ["view", "skills", "version"], 45000);
    const version = (result.stdout || result.stderr).trim();
    return {
      id: "skillsPackage",
      label: "skills package",
      status: "ok",
      detail: version
        ? args.tr("npm package available: skills@{0}", String(version))
        : args.tr("npm package lookup completed.")
    };
  } catch (error) {
    return {
      id: "skillsPackage",
      label: "skills package",
      status: "warn",
      detail: `${args.tr("Could not verify the npm skills package. Check network or npm registry settings before installing.")} ${args.toUserError(error)}`
    };
  }
}

async function runCommand(command: string, args: string[], timeout: number): Promise<CommandResult> {
  return await new Promise((resolve, reject) => {
    const executable = process.platform === "win32" ? process.env.ComSpec || "cmd.exe" : command;
    const commandArgs = process.platform === "win32" ? ["/d", "/s", "/c", command, ...args] : args;
    const child = spawn(executable, commandArgs, {
      shell: false,
      windowsHide: process.platform === "win32",
      timeout,
      env: { ...process.env, NO_COLOR: "1", FORCE_COLOR: "0" }
    });
    let stdout = "";
    let stderr = "";
    child.stdout?.on("data", (chunk: Buffer | string) => {
      stdout += chunk.toString();
    });
    child.stderr?.on("data", (chunk: Buffer | string) => {
      stderr += chunk.toString();
    });
    child.on("error", reject);
    child.on("close", (code) => {
      if (code === 0) {
        resolve({ stdout, stderr });
        return;
      }
      reject(new Error((stderr || stdout).trim() || `${command} exited with code ${code ?? 1}`));
    });
  });
}

function parseMajorVersion(value: string): number | null {
  const match = value.trim().match(/^v?(\d+)/);
  if (!match) return null;
  const parsed = Number.parseInt(match[1], 10);
  return Number.isFinite(parsed) ? parsed : null;
}

function osLabel(): string {
  if (process.platform === "win32") return "Windows";
  if (process.platform === "darwin") return "macOS";
  if (process.platform === "linux") return "Linux";
  return process.platform;
}

function nodeInstallScript(): string {
  if (process.platform === "win32") {
    return "winget install OpenJS.NodeJS.LTS\n# Restart VS Code or open a new terminal, then run:\nnode --version\nnpm --version\nnpx --version";
  }
  if (process.platform === "darwin") {
    return "brew install node\n# Restart VS Code or open a new terminal, then run:\nnode --version\nnpm --version\nnpx --version";
  }
  if (process.platform === "linux") {
    return [
      "if command -v apt-get >/dev/null 2>&1; then",
      "  sudo apt-get update && sudo apt-get install -y nodejs npm",
      "elif command -v dnf >/dev/null 2>&1; then",
      "  sudo dnf install -y nodejs npm",
      "elif command -v pacman >/dev/null 2>&1; then",
      "  sudo pacman -S --needed nodejs npm",
      "else",
      "  echo \"Install Node.js 18+ and npm with your OS package manager.\"",
      "fi",
      "node --version",
      "npm --version",
      "npx --version"
    ].join("\n");
  }
  return "Install Node.js 18+ and npm, then restart VS Code.";
}

function gitInstallScript(): string {
  if (process.platform === "win32") {
    return "winget install Git.Git\n# Restart VS Code or open a new terminal, then run:\ngit --version";
  }
  if (process.platform === "darwin") {
    return "brew install git\ngit --version";
  }
  if (process.platform === "linux") {
    return [
      "if command -v apt-get >/dev/null 2>&1; then",
      "  sudo apt-get update && sudo apt-get install -y git",
      "elif command -v dnf >/dev/null 2>&1; then",
      "  sudo dnf install -y git",
      "elif command -v pacman >/dev/null 2>&1; then",
      "  sudo pacman -S --needed git",
      "else",
      "  echo \"Install Git with your OS package manager.\"",
      "fi",
      "git --version"
    ].join("\n");
  }
  return "Install Git, then restart VS Code.";
}
